### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by XeroCheeze** [gamesir123/app#1]
Two bugs with 3.7.5.
Left click with mouse cursor visible also triggers left mouse mapped button which if playing a shooter game is fire button so whenever you are using cursor and clicking it is also shooting.

Also no way of hiding the buttons mapped on screen without the eye icon. One handed keyboards without the F hotkeys cannot hide the icons with 3.7.5.

Older version like 3.6 and 3.5 should be updated for Android 10 these versions ran the best for me. Please update 3.6.3 and 3.5.3 for Android 10.

**Comment by danilkaximka** [comment]
Подтверждаю есть такая проблемма на игровых лапах х1 и также z1 как при перетаскивании курсором мыши срабатывает кнопка огонь .
Есть много проблемм с синхронизацией приложения на 10 андройде , проблемма маппинга ..и так далее .
Присоединяйтесь к нашей русской группе в телеграмм 
@gamesirworldrus

**Comment by gamesir123** [comment]
The problem has been fixed. Please update to the latest version. Thank you for your support.

**Comment by headshot2020** [comment]
Still dont work...

**Comment by danilkaximka** [comment]
pay attention to the problem on versions of GSW 376, the problem in obtaining mapping on devices such as X1 Z1 and G5. Yes, these are devices that can receive mapping from the device’s board, but with the latest updates, problems arise above GSW 370
