### ISSUE TITLE
[question] x2 key mapping

### ISSUE THREAD

**Issue by leftstick** [gamesir123/app#36]
x2的右侧键位是switch布局，即：上->X，左->Y，下->B，右A。出了ns外，玩其他模拟器时因为映射关系问题，操作都显得很别扭。

小鸡模拟器是可以修改映射关系的，这个很好，但也只能作用在小鸡模拟器之内。

我想问问有没有办法，将映射关系应用在系统全局的？这样其他那些不支持键位映射调整的模拟器也可以愉快玩耍了

**Comment by mmmssa** [comment]
用Gtouch模式改按键映射就行了吧。

**Comment by leftstick** [comment]
我在呆萌模拟器里试了下，改成gtouch模式后，手柄就完全不起作用了。。。貌似时呆萌模拟器连上手柄以后就必须是直连模式吧。

所以才想问问有没有什么办法改一改。

因为小鸡模拟器里可以调整键位映射关系，就很方便。可惜那个功能仅能作用在小鸡模拟器里的游戏。对其他模拟器无效

**Comment by leftstick** [comment]
@gamesir123 @chenzhiwei-github 能否在游戏世界的固件相关里增加一个物理按键映射功能，这样的话，从游戏世界里启动其他游戏也都可以享受修正后的映射关系了。谢谢

![S01214-15351758](https://user-images.githubusercontent.com/1059956/102053362-95533300-3e22-11eb-8b88-74f6d7b4343a.png)

**Comment by mmmssa** [comment]
我这里按 home+G 切换到先gtouch模式，在游戏世界里点击呆萌模拟器图标，进到呆萌模拟器里，通过点左上角的小鸡手柄图标，拖出来按键到具体位置后，点击保存到外设，保存完发现是可以用的。

**Comment by leftstick** [comment]
@mmmssa 谢谢，我试了下gtouch也可以了。有些游戏用gtouch体验不够好，例如：呆萌里，用gtouch的话就必须显示虚拟手柄，看着有点碍事。

还比如死亡细胞，如果换成gtouch模式，就得手柄和触屏共同使用了。

不论如何，我也不纠结这些小事情了，非常感谢。


当然，如果官方能提供修改键位映射就最好了，哈哈哈

**Comment by gamesir123** [comment]
@leftstick 最新版4.1.1游戏世界已经支持调整按键布局了，可以去下载试下，安装最新版后，升级固件至1.15-1.3。即可设置全局更改布局。

**Comment by leftstick** [comment]
@gamesir123 666
