### ISSUE TITLE
App don't detect floating windows is activated.

### ISSUE THREAD

**Issue by diamerico** [gamesir123/app#47]
I know floating windows is working because I use Vanced, Twitch and other apps that let me do floating windows, and I don't know what changed because 2 months ago It was working perfect. Im using joyui 12, that is almost the same as miui 12.

Edit: in joiui you need to activate floating windows 2 times, first in the app management and second in special app access. I don't know why they made it so hard.

**Comment by AndrewSpec** [comment]
I can't get that working on my Mi 11. But it's as always in chineese companies. You get a product with almost zero support.

**Comment by AndrewSpec** [comment]
I know that it's closed but need to add my thougts. So after the MIUI 12.5 update it seems that it's working now.

**Comment by ChrisnaBadar** [comment]
@AndrewSpec I'm on miui 12.5 but not showing any floating... which gamesir world version you used?

**Comment by AndrewSpec** [comment]
> @AndrewSpec I'm on miui 12.5 but not showing any floating... which gamesir world version you used?

Currently I can't use it because on Android 12 this shitty gamepad just don't work.
