### ISSUE TITLE
App reconized as a threat

### ISSUE THREAD

**Issue by gspereira** [gamesir123/app#56]
I have an S21, I failed to find the app on the play store, and downloaded the APK from here.
Every 10 minutes the google play protect says this app is dangerous, and should be removed.
Why are that? Is the app using anything that it shouldn't?

**Comment by gamesir123** [comment]
You can download Gamesir from [here](https://play.google.com/store/apps/details?id=com.xiaoji.xtouch.google) which does not contain the feature of mapping activation.
