### ISSUE TITLE
I can't update GameSir X2 Bluetooth

### ISSUE THREAD

**Issue by MiguelCardonaG** [gamesir123/app#86]
I do not know what happened but this morning I went to see if there was any update and I got an error message.

![Screenshot_20220306-165423_GameSir](https://user-images.githubusercontent.com/65356692/156931112-11a8bf44-b3c9-459f-8416-2a26f527f0d0.jpg)

**Comment by Arigmr** [comment]
No se si te sirva el dato pero me paso exactamente lo mismo , tardaba mucho en actualizar y daba error , lo que hice fue conectar el joystic mediante cable usb c directo al celular y después de algunos intentos empezó a actualizar

**Comment by agus2894** [comment]
Solo lo conéctaste? O descargaste algún firmware?

**Comment by Arigmr** [comment]
Lo conecte y seguí probando de actualizar normalmente , tardaba y de a ratos se encendía la luz roja en el mando , después de un rato la aplicación detecto el mando correctamente y calculo que fue gracias a estar conectado físicamente y ahí empezó a bajar el firmware y se actualizo

**Comment by agus2894** [comment]
![Screenshot_20220310-111434](https://user-images.githubusercontent.com/101313663/157679917-ed38e699-b5a6-4a73-a806-83eb1911154a.png)
A mí se me complica más

**Comment by MiguelCardonaG** [comment]
Lo he devuelto a Amazon y hoy ya me han traído otro nuevo.
