### ISSUE TITLE
All versions of the application do not work on Android 12, should we stop using Gamesir?

### ISSUE THREAD

**Issue by BANDARALJOHANI** [gamesir123/app#99]
Are we looking for other companies? Or is there a solution soon?

**Comment by JayFADEawayy** [comment]
Other companies. Absolutely.

**Comment by BANDARALJOHANI** [comment]
> شركات أخرى. قطعاً.

much is available

**Comment by Elderon96** [comment]
4.2.9 has been released

**Comment by JayFADEawayy** [comment]
> 4.2.9 has been released

Yeah it has but only 1 side of my screen seems to be working no matter what I do.

**Comment by Pixel4aUser** [comment]
> 4.2.9 has been released

Does it work on your phone?
would you mind sharing your phone and android version?

**Comment by BANDARALJOHANI** [comment]
The latest version 4.2.9 works on Android 12

**Comment by Elderon96** [comment]
> > 4.2.9 has been released
> 
> Yeah it has but only 1 side of my screen seems to be working no matter what I do.

Have you tried turning on "intensive mapping" on the in game drop down menu?
